### PR TITLE
KeywordCompletionProvider: added Nette 3 keys

### PR DESCRIPTION
**Pull request by dg**

### CODE REVIEW

**Comment by dg** [comment]
@matej21 Is it ok?

**Comment by dg** [comment]
Can you please check it? @matej21 @juzna

**Comment by dg** [comment]
Ping @matej21

**Comment by matej21** [comment]
merged 74265f8ee3f7fa47a76abb42b8a8d07001edefb7

**Comment by dg** [comment]
🎆

**Comment by matej21** [comment]
also, update is available in plugin marketplace

**Pull request closed without merging**
